version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-drawapp}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER:-postgres}"]
      interval: 5s
      timeout: 3s
      retries: 20

  migrate:
    build:
      context: .
      dockerfile: apps/http-backend/Dockerfile
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: sh -lc "pnpm -F @repo/db prisma:migrate:deploy"

  http:
    build:
      context: .
      dockerfile: apps/http-backend/Dockerfile
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      db:
        condition: service_healthy
      migrate:
        condition: service_completed_successfully

  ws:
    build:
      context: .
      dockerfile: apps/ws-backend/Dockerfile
    env_file:
      - .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy

  web:
    build:
      context: .
      dockerfile: apps/exiledraw-frontend/Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      http:
        condition: service_started
      ws:
        condition: service_started

volumes:
  db_data:

